services:
  - type: web
    name: employee-onboarding-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: employee-db
          property: connectionString

databases:
  - name: employee-db
    databaseName: employeedb
    user: employeeuser
