services:
  - type: web
    name: employee-onboarding-backend
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: employee-db
          property: connectionString

databases:
  - name: employee-db
    databaseName: employeedb
    user: employeeuser
